"""links table

Revision ID: e32182dbe18f
Revises: 
Create Date: 2019-12-04 02:41:33.373964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e32182dbe18f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortLink', sa.String(length=64), nullable=True),
    sa.Column('longLink', sa.UnicodeText(), nullable=True),
    sa.Column('genTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_shortLink'), 'links', ['shortLink'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_shortLink'), table_name='links')
    op.drop_table('links')
    # ### end Alembic commands ###
